# Lint markdown files

name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: markdown-lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: '**/*.md'
